{% set name = "cached_property" %}
{% set version = "1.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/57/8e/0698e10350a57d46b3bcfe8eff1d4181642fd1724073336079cb13c5cf7f/{{ name }}-{{ version }}.tar.gz
  sha256: 9217a59f14a5682da7c4b8829deadbfc194ac22e9908ccf7c8820234e80a1504

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cached_property

about:
  home: https://github.com/pydanny/cached-property
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: A decorator for caching properties in classes.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - CyrilleBonamy
